# Generated by Django 4.2.3 on 2023-07-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookTracker', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='activelyReading',
        ),
        migrations.RemoveField(
            model_name='book',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='toRead',
        ),
    ]
